name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master
      - "releases/*"

jobs:
  # test action works running from the graph
  broken-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - uses: ./
        with:
          checkName: 'broken-test'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
