name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master
      - "releases/*"

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - uses: ./
        with:
          checkName: lint
          isTest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
